/**
 * Formation Étoile Bleue Urgence — données des slides
 * Captures : déposer dans /screenshots/ (voir README)
 */
const SLIDES = [
  {
    id: 1,
    title: 'Étoile Bleue Urgence',
    shortTitle: 'Introduction',
    category: 'intro',
    layout: 'hero',
    subtitle: 'Formation terrain — Application mobile urgentiste',
    lead: 'L\'application qui connecte les équipes d\'intervention à la centrale de régulation et aux hôpitaux partenaires, du dispatch à la clôture de mission.',
    stats: [
      { value: '~1 h', label: 'Durée session' },
      { value: '4', label: 'Acteurs du flux' },
      { value: 'A → Z', label: 'Cycle mission' },
    ],
    bullets: [
      'Public : secouristes et urgentistes sur le terrain',
      'Objectif : maîtriser le parcours complet d\'une intervention',
      'Format : présentation guidée + démo live + atelier pratique + Q&R',
    ],
    notes: 'Rappeler que l\'app est connectée en temps réel à la centrale (CRRA) et aux hôpitaux partenaires. Demander qui a déjà utilisé l\'app.',
  },
  {
    id: 2,
    title: 'Un outil mission critique',
    shortTitle: 'Pourquoi',
    category: 'intro',
    layout: 'feature-cards',
    lead: 'Sur le terrain, chaque minute compte. L\'application centralise ce qui était dispersé entre appels, papier et messages — pour une prise en charge traçable et coordonnée.',
    cards: [
      { icon: '🔔', title: 'Alertes en temps réel', desc: 'Recevoir les missions dispatchées par la centrale, avec son et notification plein écran.' },
      { icon: '📍', title: 'Position & disponibilité', desc: 'Signaler sa disponibilité et partager le GPS uniquement quand le service est activé.' },
      { icon: '📋', title: 'Bilan clinique terrain', desc: 'Documenter ABCDE, constantes, soins et décisions dans un dossier médical structuré.' },
      { icon: '🏥', title: 'Orientation patient', desc: 'Choisir la structure adaptée et assurer la continuité des soins jusqu\'à l\'admission.' },
    ],
    notes: 'L\'app remplace le papier et les appels dispersés par un flux unique traçable. Insister sur la valeur pour le rapport d\'intervention et la coordination.',
  },
  {
    id: 3,
    title: 'Qui utilise quoi ?',
    shortTitle: 'Écosystème',
    category: 'intro',
    layout: 'ecosystem',
    lead: 'Quatre interfaces complémentaires forment la chaîne de secours numérique. Votre rôle : l\'étape terrain entre le dispatch et l\'admission hôpital.',
    notes: 'Montrer le schéma : Citoyen → Centrale → Vous → Hôpital. Chaque acteur voit uniquement ce dont il a besoin.',
  },
  {
    id: 4,
    title: 'Se connecter en toute sécurité',
    shortTitle: 'Connexion',
    category: 'app',
    layout: 'split-phone',
    screenshot: '04-login.jpg',
    screenshotLabel: 'Écran de connexion',
    lead: 'Chaque agent dispose d\'un identifiant personnel. La connexion est requise avant toute utilisation — sans session active, aucune mission n\'est accessible.',
    bullets: [
      'Identifiant agent : <strong>6 chiffres</strong> (fourni par votre référent)',
      'Code PIN : <strong>6 chiffres</strong> — personnel et confidentiel',
      'Message affiché : « ETOILE BLEUE URGENCE — Connexion sécurisée des équipes d\'intervention »',
      'Ne jamais partager son PIN, même avec un collègue',
      'Session expirée ou app fermée → reconnecter avant de reprendre',
    ],
    notes: 'Démo : montrer l\'écran de login sur un téléphone. Vérifier que chaque binôme a bien ses identifiants test.',
  },
  {
    id: 5,
    title: '4 onglets au quotidien',
    shortTitle: 'Navigation',
    category: 'app',
    layout: 'split-phone',
    screenshot: '05-tabs.jpg',
    screenshotLabel: 'Barre d\'onglets',
    lead: 'L\'interface repose sur quatre onglets permanents. L\'accueil concentre l\'essentiel de votre garde ; les autres complètent selon le contexte.',
    table: [
      ['Accueil', 'Service, alertes entrantes, mission en cours'],
      ['Carte', 'Vue tactique : incidents, hôpitaux, collègues en service'],
      ['Historique', 'Interventions passées, appels et rapports PDF'],
      ['Profil', 'Unité, disponibilité, protocoles et statistiques'],
    ],
    notes: 'L\'accueil est le point de départ de chaque garde. Montrer comment basculer entre les onglets sans perdre une mission en cours.',
  },
  {
    id: 6,
    title: 'Avant toute mission : activer le service',
    shortTitle: 'Mise en service',
    category: 'app',
    layout: 'split-phone',
    screenshot: '06-service.jpg',
    screenshotLabel: 'Accueil — service activé',
    lead: 'C\'est la première action en début de garde. Tant que le service n\'est pas activé, la centrale ne peut ni vous localiser ni vous dispatcher.',
    bullets: [
      'Bouton maintenu : <strong>ACTIVER LE SERVICE</strong> / <strong>DÉSACTIVER LE SERVICE</strong>',
      'États visibles : <em>Prêt pour intervention</em> · <em>Service désactivé</em> · <em>Hors ligne</em>',
      'Le GPS n\'est transmis qu\'<strong>en service</strong> — respect de la vie privée hors garde',
      'Activation/désactivation aussi dans <strong>Profil</strong> (verrouillé pendant une mission active)',
    ],
    callout: 'Règle d\'or : pas de service = pas d\'alerte = pas de dispatch.',
    notes: 'Démo : activer/désactiver le service, montrer le changement d\'état et l\'impact sur la carte centrale.',
  },
  {
    id: 7,
    title: 'De l\'alerte à la clôture',
    shortTitle: 'Cycle mission',
    category: 'flow',
    layout: 'mission-flow',
    lead: 'Fil rouge de la formation — chaque étape correspond à un écran de l\'application. Revenez à ce schéma après chaque section pour situer où vous en êtes.',
    notes: 'Fil rouge de la formation — revenir à ce schéma après chaque section. Demander aux participants de mémoriser les 7 étapes clés.',
  },
  {
    id: 8,
    title: 'Quand la centrale vous assigne une mission',
    shortTitle: 'Alerte',
    category: 'app',
    layout: 'split-phone',
    screenshot: '08-alerte.jpg',
    screenshotLabel: 'Modal alerte mission',
    lead: 'Une alerte sonore retentit et un modal plein écran apparaît. Vous devez accepter ou refuser dans le délai imparti — le refus est tracé et motivé.',
    bullets: [
      'Alarme sonore + modal plein écran impossible à ignorer',
      '<strong>ACCEPTER LA MISSION</strong> ou <strong>REFUSER LA MISSION</strong>',
      'Compte à rebours visible si délai d\'acceptation limité',
      'Refus = motif obligatoire : Indisponible · Trop loin · Véhicule en panne · Capacité insuffisante · Autre',
    ],
    callout: 'Mieux vaut refuser honnêtement que d\'accepter sans pouvoir intervenir dans les délais.',
    notes: 'Le refus est tracé côté centrale. Discuter des cas où refuser est la bonne décision.',
  },
  {
    id: 9,
    title: 'Reprendre où vous en étiez',
    shortTitle: 'Mission en cours',
    category: 'app',
    layout: 'split-phone',
    screenshot: '09-intervention.jpg',
    screenshotLabel: 'Intervention en cours',
    lead: 'L\'accueil affiche toujours l\'état de votre mission active. L\'application sauvegarde votre progression — fermer l\'app ne fait pas perdre le dossier.',
    bullets: [
      '<strong>AFFICHER L\'ALERTE</strong> — mission reçue mais pas encore acceptée',
      '<strong>CONTINUER LE PROCESSUS</strong> — reprise avec sous-titre <em>Étape — …</em>',
      'Exemples : Direction vers patient · Évaluation du patient · 3 patients en traitement',
      'Reconnexion automatique à la dernière étape après redémarrage de l\'app',
    ],
    notes: 'Montrer la carte intervention en cours sur l\'accueil. Simuler une fermeture/réouverture de l\'app.',
  },
  {
    id: 10,
    title: 'Écran Mission Active',
    shortTitle: 'En route',
    category: 'app',
    layout: 'split-phone',
    screenshot: '10-mission-active.jpg',
    screenshotLabel: 'Navigation GPS',
    lead: 'Une fois la mission acceptée, cet écran devient votre tableau de bord : navigation, statut, journal et communications regroupés.',
    bullets: [
      'Carte GPS plein écran avec itinéraire vers le patient',
      'Statuts successifs : <em>Dispatché</em> → <em>En route</em> → <em>Sur zone</em> → <em>Terminé</em>',
      'Journal d\'intervention accessible en un tap',
      'Appels vers centrale, patient ou hôpital depuis le HUD',
      'Bouton <strong>Arrivée sur site ?</strong> — à confirmer avant de commencer le bilan',
    ],
    notes: 'Montrer la carte, l\'ETA et le bouton d\'arrivée sur site. Insister : ne pas sauter « Arrivée sur site ».',
  },
  {
    id: 11,
    title: 'Le cœur clinique de l\'intervention',
    shortTitle: 'Signalement',
    category: 'app',
    layout: 'split-phone',
    screenshot: '11-signalement.jpg',
    screenshotLabel: 'Étapes Signalement',
    lead: 'Le Signalement est le dossier médical terrain complet. Chaque étape correspond à une phase clinique — vous avancez linéairement, avec possibilité de revenir en arrière.',
    table: [
      ['En route', 'Direction vers le lieu de l\'incident'],
      ['Victimes sur site', 'Mono-victime ou afflux massif'],
      ['Évaluation', 'Bilan ABCDE structuré'],
      ['Surveillance', 'Suivi clinique continu'],
      ['Constantes', 'Paramètres vitaux et timeline'],
      ['Premiers soins', 'Gestes réalisés et médicaments'],
      ['Plan d\'évacuation', 'Transport ou traité sur place'],
      ['Affectation', 'Choix de la structure de destination'],
      ['Attente admission', 'Remise au personnel hospitalier'],
      ['Clôture', 'Fin d\'intervention pour cette victime'],
    ],
    notes: 'Le Signalement est le dossier médical terrain complet. Montrer la barre de progression des étapes.',
  },
  {
    id: 12,
    title: 'Une ou plusieurs victimes ?',
    shortTitle: 'Victimes',
    category: 'app',
    layout: 'split-phone',
    screenshot: '12-victimes.jpg',
    screenshotLabel: 'Choix mono / multi',
    lead: 'Le type d\'incident détermine le parcours. En afflux massif, chaque victime dispose de son propre dossier clinique indépendant.',
    bullets: [
      '<strong>Une seule victime</strong> : flux classique (appel citoyen, accident isolé)',
      '<strong>Plusieurs victimes / Afflux massif</strong> : hub patients dédié avec bascule rapide',
      'Navigation entre victimes via le compteur <em>N patients en traitement</em>',
      'Profil modifiable par victime : âge, sexe, code d\'affichage',
    ],
    notes: 'En afflux, chaque victime a son propre parcours clinique. Ne pas mélanger les bilans entre patients.',
  },
  {
    id: 13,
    title: 'Bilan structuré ABCDE',
    shortTitle: 'ABCDE',
    category: 'app',
    layout: 'split-phone',
    screenshot: '13-abcde.jpg',
    screenshotLabel: 'Évaluation ABCDE',
    lead: 'L\'évaluation suit la méthode ABCDE standard. Le questionnaire s\'adapte au type d\'incident et propose une classification de triage.',
    bullets: [
      '<strong>A</strong> — Voies aériennes : perméabilité, obstruction',
      '<strong>B</strong> — Respiration : fréquence, effort, SpO₂',
      '<strong>C</strong> — Circulation : pouls, hémorragie, perfusion',
      '<strong>D</strong> — Conscience / neurologique : AVPU, pupilles',
      '<strong>E</strong> — Exposition : température, lésions, environnement',
    ],
    triage: [
      { color: 'red', label: 'Rouge — Immédiat (urgence vitale)' },
      { color: 'orange', label: 'Orange — Très urgent' },
      { color: 'yellow', label: 'Jaune — Urgent' },
      { color: 'green', label: 'Vert — Non urgent' },
    ],
    notes: 'Questionnaire dynamique selon le type d\'incident. Rappeler que le triage peut être réévalué à tout moment.',
  },
  {
    id: 14,
    title: 'Documenter l\'évolution',
    shortTitle: 'Constantes',
    category: 'app',
    layout: 'split-phone',
    screenshot: '14-constantes.jpg',
    screenshotLabel: 'Constantes vitales',
    lead: 'Les constantes vitales alimentent une timeline clinique horodatée. L\'application signale les valeurs hors norme et suggère une reclassification du triage.',
    bullets: [
      'Saisie : tension · fréq. cardiaque · SpO₂ · température · fréq. resp. · glycémie',
      'Timeline chronologique : évaluations, gestes et traitements',
      'Alertes automatiques : <em>Points d\'attention sur les constantes saisies</em>',
      'Suggestions de reclassification si l\'état du patient évolue',
    ],
    notes: 'Réévaluer régulièrement. La timeline alimente directement le rapport PDF final.',
  },
  {
    id: 15,
    title: 'Gestes et médicaments',
    shortTitle: 'Premiers soins',
    category: 'app',
    layout: 'split-phone',
    screenshot: '15-soins.jpg',
    screenshotLabel: 'Premiers soins',
    lead: 'Cochez chaque geste réalisé et enregistrez les médicaments administrés. Tout est horodaté dans le journal pour une traçabilité complète.',
    bullets: [
      'Checklist des soins réalisés sur le terrain',
      'Prescriptions avec aide contextuelle sur les voies d\'administration',
      'Horodatage automatique de chaque action dans le journal d\'intervention',
    ],
    callout: 'Outil de traçabilité — pas un substitut au jugement clinique du secouriste.',
    notes: 'Outil de traçabilité — pas un substitut au jugement clinique. Montrer l\'ajout d\'un soin et sa trace dans le journal.',
  },
  {
    id: 16,
    title: 'Décision structurante',
    shortTitle: 'Évacuation',
    category: 'app',
    layout: 'split-phone',
    screenshot: '16-evacuation.jpg',
    screenshotLabel: 'Plan d\'évacuation',
    lead: 'Après stabilisation, deux issues possibles. Ce choix oriente la suite du parcours — évacuation ou clôture sur place.',
    bullets: [
      '<strong>Évacuation vers un hôpital</strong> → suite du flux : affectation, transport, admission',
      '<strong>Traité sur place</strong> → clôture victime puis mission, si le patient est stable',
    ],
    callout: 'Traité sur place = patient stable, pas besoin de structure hospitalière. Documenter la décision et les constantes finales.',
    notes: 'Traité sur place = patient stable, pas besoin de structure. Bien documenter la justification clinique.',
  },
  {
    id: 17,
    title: 'Choisir la destination',
    shortTitle: 'Affectation',
    category: 'app',
    layout: 'split-phone',
    screenshot: '17-hopital.jpg',
    screenshotLabel: 'Sélection hôpital',
    lead: 'La liste des structures proches s\'affiche avec leur disponibilité. Le choix dépend du profil du patient, pas seulement de la distance.',
    bullets: [
      'Liste des hôpitaux à proximité + barre de recherche',
      'États en temps réel : En attente · <strong>Demande refusée</strong> · Acceptée',
      'Modes de transport : Ambulance standard · SMUR/Réa · Moto · Transport personnel',
    ],
    notes: 'Démo : parcours de sélection d\'un hôpital en environnement de test. Discuter critères de choix (spécialité, saturation).',
  },
  {
    id: 18,
    title: 'Ce que voit l\'hôpital',
    shortTitle: 'Handoff',
    category: 'app',
    layout: 'split-phone',
    screenshot: '18-hopital-portail.jpg',
    screenshotLabel: 'Portail hôpital',
    lead: 'Pendant que vous attendez, l\'hôpital consulte le portail admission. L\'acceptation à distance ne remplace pas la remise physique du patient.',
    table: [
      ['Demandes', 'L\'hôpital accepte ou refuse votre demande d\'admission'],
      ['En route', 'Suivi du patient en approche avec ETA'],
      ['Admissions', 'Triage hospitalier et prise en charge effective'],
    ],
    bullets: ['Côté urgentiste : statut <em>En attente de confirmation hôpital…</em> jusqu\'à validation'],
    notes: 'La remise physique du patient est distincte de l\'acceptation à distance. Ne pas clôturer avant les deux.',
  },
  {
    id: 19,
    title: 'Navigation vers la structure',
    shortTitle: 'Transport',
    category: 'app',
    layout: 'split-phone',
    screenshot: '19-transport.jpg',
    screenshotLabel: 'Vers l\'hôpital',
    lead: 'Une fois l\'hôpital accepté, la navigation GPS vous guide vers la structure. Vous pouvez basculer vers Waze ou Google Maps si besoin.',
    bullets: [
      'Navigation GPS intégrée vers la structure choisie',
      'Ouverture possible dans Waze / Google Maps (app externe)',
      'Confirmation à l\'arrivée : <strong>Arrivé à l\'hôpital ?</strong>',
      'Puis étape <strong>Attente admission</strong> — remise du patient au personnel',
    ],
    notes: 'Ne pas clôturer avant confirmation de prise en charge par l\'hôpital. Montrer le basculement GPS externe.',
  },
  {
    id: 20,
    title: 'Fin d\'intervention',
    shortTitle: 'Clôture',
    category: 'app',
    layout: 'split-phone',
    screenshot: '20-cloture.jpg',
    screenshotLabel: 'Clôture mission',
    lead: 'La clôture synchronise le dossier avec la centrale et archive la mission. Le rapport PDF est disponible immédiatement dans l\'historique.',
    bullets: [
      'Écran de clôture avec synchronisation (<em>Clôture en cours…</em>)',
      'Mission archivée dans <strong>Historique → Interventions</strong>',
      'Rapport consultable : export <strong>PDF</strong> et impression',
    ],
    notes: 'Vérifier que toutes les victimes sont clôturées en cas d\'afflux. Montrer le PDF généré.',
  },
  {
    id: 21,
    title: 'Appeler sans quitter l\'app',
    shortTitle: 'Communication',
    category: 'app',
    layout: 'split-phone',
    screenshot: '21-appels.jpg',
    screenshotLabel: 'Appels intégrés',
    lead: 'Les communications sont intégrées à l\'application — pas besoin de quitter la mission pour contacter la centrale, le patient ou l\'hôpital.',
    table: [
      ['Centrale', 'Depuis l\'accueil ou le HUD mission active'],
      ['Patient', 'VoIP / GSM depuis le journal d\'intervention'],
      ['Hôpital', 'Disponible une fois la structure acceptée'],
    ],
    bullets: [
      'Barre d\'appel flottante pendant toute la communication',
      'Appels entrants gérés nativement (Android / iOS)',
    ],
    notes: 'Montrer le bouton d\'appel centrale sans lancer un vrai appel si possible.',
  },
  {
    id: 22,
    title: 'Mémoire de la mission',
    shortTitle: 'Journal',
    category: 'app',
    layout: 'split-phone',
    screenshot: '22-journal.jpg',
    screenshotLabel: 'Journal d\'intervention',
    lead: 'Le journal retrace chronologiquement tout ce qui s\'est passé : actions automatiques, notes manuelles et photos terrain. Il est synchronisé avec la centrale.',
    bullets: [
      'Fil chronologique horodaté de toutes les actions',
      'Notes manuelles et photos terrain ajoutables à tout moment',
      'Accessible depuis Accueil, Signalement et Mission Active',
      'Synchronisé en temps réel avec la centrale de régulation',
    ],
    notes: 'Utile pour le rapport final et en cas de litige. Montrer l\'ajout d\'une note manuelle.',
  },
  {
    id: 23,
    title: 'Vue d\'ensemble du terrain',
    shortTitle: 'Carte',
    category: 'app',
    layout: 'split-phone',
    screenshot: '23-carte.jpg',
    screenshotLabel: 'Carte tactique',
    lead: 'La carte tactique donne une vision globale : incidents en cours, structures sanitaires et collègues en service. Complément utile, pas un substitut à la mission active.',
    bullets: [
      'Incidents en cours avec localisation',
      'Structures sanitaires : hôpital, pharmacie, centre de santé, maternité',
      'Autres secouristes en service (position en temps réel)',
      'Calcul d\'itinéraires vers n\'importe quel point',
    ],
    notes: 'Complément à Mission Active, pas un substitut. Utile pour repérer un hôpital ou un collègue proche.',
  },
  {
    id: 24,
    title: 'Profil et ressources',
    shortTitle: 'Outils',
    category: 'app',
    layout: 'split-phone',
    screenshot: '24-profil.jpg',
    screenshotLabel: 'Profil & outils',
    lead: 'Le profil regroupe vos paramètres d\'unité et des ressources complémentaires accessibles en permanence, même en mission.',
    bullets: [
      '<strong>Protocoles médicaux</strong> — base documentaire RDC consultable offline',
      '<strong>Statistiques de l\'unité</strong> — missions, temps de réponse',
      '<strong>Notifications</strong> — alertes système et mises à jour',
      '<strong>Signaler un problème</strong> — véhicule, matériel, application',
      '<strong>Aide & support</strong> — FAQ et contact technique',
    ],
    notes: 'Ressources complémentaires accessibles depuis le profil. Montrer les protocoles médicaux.',
  },
  {
    id: 25,
    title: 'Checklist du urgentiste formé',
    shortTitle: 'Bonnes pratiques',
    category: 'recap',
    layout: 'checklist-good',
    lead: 'Avant de passer à l\'atelier pratique, vérifiez que ces réflexes sont acquis.',
    items: [
      'Activer le service en début de garde — c\'est la première action',
      'Vérifier connexion internet et GPS avant d\'attendre des alertes',
      'Accepter ou refuser dans les délais — le refus motivé est préférable',
      'Confirmer « Arrivée sur site » avant de commencer le bilan clinique',
      'Documenter ABCDE + constantes à chaque réévaluation',
      'Choisir l\'hôpital adapté au patient, pas seulement le plus proche',
      'Attendre la validation d\'admission avant de clôturer la mission',
      'Consulter le rapport PDF en fin de garde',
    ],
    notes: 'Slide récapitulative avant l\'atelier pratique. Demander aux participants de cocher mentalement chaque point.',
  },
  {
    id: 26,
    title: 'Erreurs fréquentes en formation',
    shortTitle: 'Erreurs',
    category: 'recap',
    layout: 'checklist-bad',
    lead: 'Ces erreurs reviennent souvent lors des premières sessions. Les connaître permet de les éviter sur le terrain.',
    items: [
      'Oublier d\'activer le service → aucune alerte reçue',
      'Clôturer avant la remise effective du patient à l\'hôpital',
      'Sauter l\'étape « Arrivée sur site » et commencer le bilan trop tôt',
      'Confondre acceptation hôpital à distance et admission physique',
      'Ne pas gérer les victimes multiples individuellement en afflux',
      'Perdre la connexion sans le savoir (indicateur « Connexion perdue »)',
    ],
    notes: 'Discuter chaque erreur avec des exemples concrets du terrain.',
  },
  {
    id: 27,
    title: 'Termes de l\'interface',
    shortTitle: 'Glossaire',
    category: 'recap',
    layout: 'glossary',
    lead: 'Référence rapide des termes affichés dans l\'application et leur signification opérationnelle.',
    table: [
      ['En service / Hors service', 'Disponibilité pour recevoir un dispatch'],
      ['Dispatché', 'Mission assignée, en route vers le patient'],
      ['Sur zone', 'Présent sur les lieux de l\'incident'],
      ['Signalement', 'Flux clinique complet du dossier patient'],
      ['Affectation', 'Choix de la structure hospitalière de destination'],
      ['Remise du patient', 'Transfert physique et administratif à l\'hôpital'],
      ['Afflux massif', 'Incident avec plusieurs victimes simultanées'],
    ],
    notes: 'Distribuer en fiche mémo si besoin. Bon support pour les nouvelles recrues.',
  },
  {
    id: 28,
    title: 'Scénario guidé — 15 min',
    shortTitle: 'Atelier',
    category: 'recap',
    layout: 'numbered',
    lead: 'Chaque binôme réalise ce parcours complet sur un compte test, supervisé par le formateur.',
    steps: [
      'Connexion + activation du service',
      'Accepter une mission test dispatchée',
      'Simuler l\'arrivée sur site',
      'Remplir un bilan ABCDE (victime fictive)',
      'Choisir évacuation + hôpital test',
      'Simuler arrivée hôpital + clôture mission',
    ],
    bullets: ['Matériel : 1 téléphone par binôme, comptes test fournis par le formateur.'],
    notes: 'Superviser les binômes et corriger les erreurs en direct. Prévoir 15 min + 5 min de debrief.',
  },
  {
    id: 29,
    title: 'Besoin d\'aide ?',
    shortTitle: 'Support',
    category: 'recap',
    layout: 'bullets',
    lead: 'Des questions après la formation ? Voici les contacts et la session de questions-réponses.',
    bullets: [
      'Support technique : <em>[à compléter — email / téléphone]</em>',
      'Référent formation : <em>[à compléter — nom et contact]</em>',
      'Session Q&R — 10 minutes pour vos questions',
    ],
    notes: 'Recueillir les retours terrain pour améliorer la prochaine session. Distribuer une fiche contact.',
  },
  {
    id: 30,
    title: 'Étoile Bleue Urgence',
    shortTitle: 'Merci',
    category: 'intro',
    layout: 'hero',
    subtitle: 'Intervenir mieux, documenter mieux, coordonner mieux.',
    lead: 'Vous disposez maintenant des clés pour utiliser l\'application en conditions réelles. La prochaine étape : une garde supervisée avec votre référent.',
    bullets: [
      'Garde supervisée avec référent terrain',
      'Support disponible en cas de difficulté',
      'Rapport PDF consultable après chaque mission',
    ],
    notes: 'Remercier les participants et confirmer la date de la garde supervisée.',
  },
];
