/**
 * Formation Étoile Bleue Urgence — données des slides
 * Captures : déposer dans /screenshots/ (voir README)
 */
const SLIDES = [
  {
    id: 1,
    title: 'Étoile Bleue Urgence',
    shortTitle: 'Introduction',
    category: 'intro',
    layout: 'hero',
    subtitle: 'Formation terrain — Application mobile urgentiste',
    bullets: [
      'Équipes d\'intervention (secouristes / urgentistes)',
      'Prise en charge d\'une mission de A à Z',
      'Durée : ~1 h (présentation + démo + Q&R)',
    ],
    notes: 'Rappeler que l\'app est connectée en temps réel à la centrale de régulation (CRRA) et aux hôpitaux partenaires.',
  },
  {
    id: 2,
    title: 'Un outil mission critique',
    shortTitle: 'Pourquoi',
    category: 'intro',
    layout: 'bullets',
    bullets: [
      'Recevoir les alertes dispatchées par la centrale',
      'Gérer sa disponibilité et sa position GPS',
      'Documenter le bilan clinique sur le terrain',
      'Orienter le patient vers la bonne structure',
      'Assurer la continuité des soins jusqu\'à l\'admission hôpital',
    ],
    notes: 'L\'app remplace le papier et les appels dispersés par un flux unique traçable.',
  },
  {
    id: 3,
    title: 'Qui utilise quoi ?',
    shortTitle: 'Écosystème',
    category: 'intro',
    layout: 'ecosystem',
    notes: 'Montrer le schéma : Citoyen → Centrale → Vous → Hôpital.',
  },
  {
    id: 4,
    title: 'Se connecter en toute sécurité',
    shortTitle: 'Connexion',
    category: 'app',
    layout: 'split-phone',
    screenshot: '04-login.png',
    screenshotLabel: 'Écran de connexion',
    bullets: [
      'Identifiant agent : <strong>6 chiffres</strong>',
      'Code PIN : <strong>6 chiffres</strong>',
      '« ETOILE BLEUE URGENCE — Connexion sécurisée des équipes d\'intervention »',
      'Ne jamais partager son PIN',
      'Perte de session → reconnecter',
    ],
    notes: 'Démo : montrer l\'écran de login sur un téléphone.',
  },
  {
    id: 5,
    title: '4 onglets au quotidien',
    shortTitle: 'Navigation',
    category: 'app',
    layout: 'split-phone',
    screenshot: '05-tabs.png',
    screenshotLabel: 'Barre d\'onglets',
    table: [
      ['Accueil', 'Service, alertes, mission en cours'],
      ['Carte', 'Vue tactique : incidents, hôpitaux, collègues'],
      ['Historique', 'Interventions passées, appels, rapports'],
      ['Profil', 'Unité, disponibilité, protocoles, stats'],
    ],
    notes: 'L\'accueil est le point de départ de chaque garde.',
  },
  {
    id: 6,
    title: 'Avant toute mission : ACTIVER LE SERVICE',
    shortTitle: 'Mise en service',
    category: 'app',
    layout: 'split-phone',
    screenshot: '06-service.png',
    screenshotLabel: 'Accueil — service activé',
    bullets: [
      'Bouton maintenu : <strong>ACTIVER LE SERVICE</strong> / <strong>DÉSACTIVER LE SERVICE</strong>',
      'États : <em>Prêt pour intervention</em> · <em>Service désactivé</em> · <em>Hors ligne</em>',
      'Le GPS n\'est envoyé qu\'<strong>en service</strong>',
      'Toggle aussi dans <strong>Profil</strong> (verrouillé pendant une mission)',
    ],
    callout: 'Règle d\'or : Pas de service = pas d\'alerte = pas de dispatch.',
    notes: 'Démo : activer/désactiver le service, montrer le changement d\'état.',
  },
  {
    id: 7,
    title: 'De l\'alerte à la clôture',
    shortTitle: 'Cycle mission',
    category: 'flow',
    layout: 'mission-flow',
    notes: 'Fil rouge de la formation — revenir à ce schéma après chaque section.',
  },
  {
    id: 8,
    title: 'Quand la centrale vous assigne une mission',
    shortTitle: 'Alerte',
    category: 'app',
    layout: 'split-phone',
    screenshot: '08-alerte.png',
    screenshotLabel: 'Modal alerte mission',
    bullets: [
      'Alarme sonore + modal plein écran',
      '<strong>ACCEPTER LA MISSION</strong> ou <strong>REFUSER LA MISSION</strong>',
      'Compte à rebours si délai d\'acceptation',
      'Refus = motif obligatoire : Indisponible · Trop loin · Véhicule en panne · Capacité insuffisante · Autre',
    ],
    notes: 'Le refus est tracé. Mieux vaut refuser que accepter sans pouvoir intervenir.',
  },
  {
    id: 9,
    title: 'Reprendre où vous en étiez',
    shortTitle: 'Mission en cours',
    category: 'app',
    layout: 'split-phone',
    screenshot: '09-intervention.png',
    screenshotLabel: 'Intervention en cours',
    bullets: [
      '<strong>AFFICHER L\'ALERTE</strong> — mission pas encore acceptée',
      '<strong>CONTINUER LE PROCESSUS</strong> — reprise avec sous-titre <em>Étape — …</em>',
      'Ex. : Direction vers patient · Évaluation du patient · 3 patients en traitement',
      'L\'app sauvegarde l\'état — fermer l\'app ne fait pas perdre la mission',
    ],
    notes: 'Montrer la carte intervention en cours sur l\'accueil.',
  },
  {
    id: 10,
    title: 'Écran Mission Active',
    shortTitle: 'En route',
    category: 'app',
    layout: 'split-phone',
    screenshot: '10-mission-active.png',
    screenshotLabel: 'Navigation GPS',
    bullets: [
      'Carte GPS plein écran + itinéraire',
      'Statuts : <em>Dispatché</em> → <em>En route</em> → <em>Sur zone</em> → <em>Terminé</em>',
      'Journal d\'intervention',
      'Appel centrale / patient / hôpital',
      '<strong>Arrivée sur site ?</strong> (confirmation)',
    ],
    notes: 'Montrer la carte, l\'ETA et le bouton d\'arrivée sur site.',
  },
  {
    id: 11,
    title: 'Le cœur clinique de l\'intervention',
    shortTitle: 'Signalement',
    category: 'app',
    layout: 'split-phone',
    screenshot: '11-signalement.png',
    screenshotLabel: 'Étapes Signalement',
    table: [
      ['En route', 'Direction vers le lieu'],
      ['Victimes sur site', 'Mono ou multi-victimes'],
      ['Évaluation', 'Bilan ABCDE'],
      ['Surveillance', 'Suivi clinique continu'],
      ['Constantes', 'Paramètres vitaux'],
      ['Premiers soins', 'Gestes + médicaments'],
      ['Plan d\'évacuation', 'Transport ou traité sur place'],
      ['Affectation', 'Choix de l\'hôpital'],
      ['Attente admission', 'Remise au personnel'],
      ['Clôture', 'Fin d\'intervention'],
    ],
    notes: 'Le Signalement est le dossier médical terrain complet.',
  },
  {
    id: 12,
    title: 'Une ou plusieurs victimes ?',
    shortTitle: 'Victimes',
    category: 'app',
    layout: 'split-phone',
    screenshot: '12-victimes.png',
    screenshotLabel: 'Choix mono / multi',
    bullets: [
      '<strong>Une seule victime</strong> : flux classique (appel citoyen)',
      '<strong>Plusieurs victimes / Afflux massif</strong> : hub patients dédié',
      'Bascule entre victimes',
      'Compteur <em>N patients en traitement</em>',
      'Profil modifiable (âge, sexe, code affichage)',
    ],
    notes: 'En afflux, chaque victime a son propre parcours clinique.',
  },
  {
    id: 13,
    title: 'Bilan structuré',
    shortTitle: 'ABCDE',
    category: 'app',
    layout: 'split-phone',
    screenshot: '13-abcde.png',
    screenshotLabel: 'Évaluation ABCDE',
    bullets: [
      '<strong>A</strong> — Voies aériennes',
      '<strong>B</strong> — Respiration',
      '<strong>C</strong> — Circulation',
      '<strong>D</strong> — Conscience / neurologique',
      '<strong>E</strong> — Exposition / environnement',
    ],
    triage: [
      { color: 'red', label: 'Rouge — Immédiat (urgence vitale)' },
      { color: 'orange', label: 'Orange — Très urgent' },
      { color: 'yellow', label: 'Jaune — Urgent' },
      { color: 'green', label: 'Vert — Non urgent' },
    ],
    notes: 'Questionnaire dynamique selon le type d\'incident.',
  },
  {
    id: 14,
    title: 'Documenter l\'évolution',
    shortTitle: 'Constantes',
    category: 'app',
    layout: 'split-phone',
    screenshot: '14-constantes.png',
    screenshotLabel: 'Constantes vitales',
    bullets: [
      'Tension · Fréq. cardiaque · Sat. O₂ · Température · Fréq. resp. · Glycémie',
      'Timeline clinique (évaluations, gestes, traitements)',
      'Alertes : <em>Points d\'attention sur les constantes saisies</em>',
      'Suggestions de reclassification du triage',
    ],
    notes: 'Réévaluer régulièrement. La timeline sert au rapport final.',
  },
  {
    id: 15,
    title: 'Gestes et médicaments',
    shortTitle: 'Premiers soins',
    category: 'app',
    layout: 'split-phone',
    screenshot: '15-soins.png',
    screenshotLabel: 'Premiers soins',
    bullets: [
      'Checklist des soins réalisés',
      'Prescriptions avec aide sur les voies d\'administration',
      'Tout est horodaté dans le journal',
    ],
    notes: 'Outil de traçabilité — pas un substitut au jugement clinique.',
  },
  {
    id: 16,
    title: 'Décision structurante',
    shortTitle: 'Évacuation',
    category: 'app',
    layout: 'split-phone',
    screenshot: '16-evacuation.png',
    screenshotLabel: 'Plan d\'évacuation',
    bullets: [
      '<strong>Évacuation vers un hôpital</strong> → suite du flux transport',
      '<strong>Traité sur place</strong> → clôture victime / mission',
    ],
    notes: 'Traité sur place = patient stable, pas besoin de structure. Bien documenter.',
  },
  {
    id: 17,
    title: 'Choisir la destination',
    shortTitle: 'Affectation',
    category: 'app',
    layout: 'split-phone',
    screenshot: '17-hopital.png',
    screenshotLabel: 'Sélection hôpital',
    bullets: [
      'Liste des hôpitaux proches + recherche',
      'États : En attente · <strong>Demande refusée</strong> · Acceptée',
      'Modes : Ambulance standard · SMUR/Réa · Moto · Transport perso',
    ],
    notes: 'Démo : parcours de sélection d\'un hôpital en environnement de test.',
  },
  {
    id: 18,
    title: 'Ce que voit l\'hôpital',
    shortTitle: 'Handoff',
    category: 'app',
    layout: 'split-phone',
    screenshot: '18-hopital-portail.png',
    screenshotLabel: 'Portail hôpital',
    table: [
      ['Demandes', 'Accepter / refuser votre demande'],
      ['En route', 'Patient en approche'],
      ['Admissions', 'Triage, prise en charge'],
    ],
    bullets: ['Vous voyez : <em>En attente de confirmation hôpital…</em> jusqu\'à validation'],
    notes: 'La remise physique du patient est distincte de l\'acceptation à distance.',
  },
  {
    id: 19,
    title: 'Navigation vers la structure',
    shortTitle: 'Transport',
    category: 'app',
    layout: 'split-phone',
    screenshot: '19-transport.png',
    screenshotLabel: 'Vers l\'hôpital',
    bullets: [
      'Navigation GPS vers la structure',
      'Possibilité d\'ouvrir Waze / Google Maps',
      'Confirmation : <strong>Arrivé à l\'hôpital ?</strong>',
      'Puis : <strong>Attente admission</strong> — Remise du patient',
    ],
    notes: 'Ne pas clôturer avant confirmation de prise en charge par l\'hôpital.',
  },
  {
    id: 20,
    title: 'Fin d\'intervention',
    shortTitle: 'Clôture',
    category: 'app',
    layout: 'split-phone',
    screenshot: '20-cloture.png',
    screenshotLabel: 'Clôture mission',
    bullets: [
      'Écran de clôture + synchronisation (<em>Clôture en cours…</em>)',
      'Mission archivée dans <strong>Historique → Interventions</strong>',
      'Rapport consultable : export <strong>PDF</strong>, impression',
    ],
    notes: 'Vérifier que toutes les victimes sont clôturées en cas d\'afflux.',
  },
  {
    id: 21,
    title: 'Appeler sans quitter l\'app',
    shortTitle: 'Communication',
    category: 'app',
    layout: 'split-phone',
    screenshot: '21-appels.png',
    screenshotLabel: 'Appels intégrés',
    table: [
      ['Centrale', 'Depuis l\'accueil ou le HUD mission'],
      ['Patient', 'VoIP / GSM depuis le journal'],
      ['Hôpital', 'Une fois structure acceptée'],
    ],
    bullets: [
      'Barre d\'appel flottante pendant la communication',
      'Appels entrants gérés nativement (Android/iOS)',
    ],
    notes: 'Montrer le bouton d\'appel centrale sans lancer un vrai appel si possible.',
  },
  {
    id: 22,
    title: 'Mémoire de la mission',
    shortTitle: 'Journal',
    category: 'app',
    layout: 'split-phone',
    screenshot: '22-journal.png',
    screenshotLabel: 'Journal d\'intervention',
    bullets: [
      'Fil chronologique horodaté',
      'Notes manuelles et photos terrain',
      'Accessible depuis Accueil, Signalement et Mission Active',
      'Synchronisé avec la centrale',
    ],
    notes: 'Utile pour le rapport et les litiges.',
  },
  {
    id: 23,
    title: 'Vue d\'ensemble du terrain',
    shortTitle: 'Carte',
    category: 'app',
    layout: 'split-phone',
    screenshot: '23-carte.png',
    screenshotLabel: 'Carte tactique',
    bullets: [
      'Incidents en cours',
      'Structures sanitaires (hôpital, pharmacie, centre de santé, maternité)',
      'Autres secouristes en service',
      'Itinéraires',
    ],
    notes: 'Complément à Mission Active, pas un substitut.',
  },
  {
    id: 24,
    title: 'Profil et ressources',
    shortTitle: 'Outils',
    category: 'app',
    layout: 'split-phone',
    screenshot: '24-profil.png',
    screenshotLabel: 'Profil & outils',
    bullets: [
      '<strong>Protocoles médicaux</strong> — base documentaire RDC',
      '<strong>Statistiques de l\'unité</strong>',
      '<strong>Notifications</strong> — alertes système',
      '<strong>Signaler un problème</strong> — véhicule, matériel',
      '<strong>Aide & support</strong>',
    ],
    notes: 'Ressources complémentaires accessibles depuis le profil.',
  },
  {
    id: 25,
    title: 'Checklist du urgentiste formé',
    shortTitle: 'Bonnes pratiques',
    category: 'recap',
    layout: 'checklist-good',
    items: [
      'Activer le service en début de garde',
      'Vérifier connexion internet + GPS',
      'Accepter/refuser dans les délais',
      'Confirmer Arrivée sur site avant le bilan',
      'Documenter ABCDE + constantes à chaque réévaluation',
      'Choisir l\'hôpital adapté, pas seulement le plus proche',
      'Attendre la validation d\'admission avant clôture',
      'Consulter le rapport en fin de garde',
    ],
    notes: 'Slide récapitulative avant l\'atelier pratique.',
  },
  {
    id: 26,
    title: 'Ce qu\'on voit en formation',
    shortTitle: 'Erreurs',
    category: 'recap',
    layout: 'checklist-bad',
    items: [
      'Oublier d\'activer le service → pas d\'alertes',
      'Clôturer avant remise effective du patient',
      'Sauter l\'étape Arrivée sur site',
      'Confondre acceptation hôpital à distance et admission physique',
      'Ne pas gérer les victimes multiples individuellement en afflux',
      'Perdre la connexion sans le savoir (Connexion perdue)',
    ],
    notes: 'Discuter chaque erreur avec des exemples concrets.',
  },
  {
    id: 27,
    title: 'Termes de l\'interface',
    shortTitle: 'Glossaire',
    category: 'recap',
    layout: 'glossary',
    table: [
      ['En service / Hors service', 'Disponibilité pour dispatch'],
      ['Dispatché', 'Mission assignée, pas encore sur zone'],
      ['Sur zone', 'Sur les lieux de l\'incident'],
      ['Signalement', 'Flux clinique complet'],
      ['Affectation', 'Choix de la structure de destination'],
      ['Remise du patient', 'Transfert physique à l\'hôpital'],
      ['Afflux massif', 'Plusieurs victimes sur un même incident'],
    ],
    notes: 'Distribuer en fiche mémo si besoin.',
  },
  {
    id: 28,
    title: 'Scénario guidé — 15 min',
    shortTitle: 'Atelier',
    category: 'recap',
    layout: 'numbered',
    steps: [
      'Connexion + activation du service',
      'Accepter une mission test',
      'Simuler arrivée sur site',
      'Remplir un bilan ABCDE (victime fictive)',
      'Choisir évacuation + hôpital test',
      'Simuler arrivée hôpital + clôture',
    ],
    bullets: ['Matériel : 1 téléphone par binôme, comptes test fournis.'],
    notes: 'Superviser les binômes et corriger les erreurs en direct.',
  },
  {
    id: 29,
    title: 'Besoin d\'aide ?',
    shortTitle: 'Support',
    category: 'recap',
    layout: 'bullets',
    bullets: [
      'Support technique : <em>[à compléter]</em>',
      'Référent formation : <em>[à compléter]</em>',
      'Q&R — 10 minutes',
    ],
    notes: 'Recueillir les retours terrain pour améliorer la prochaine session.',
  },
  {
    id: 30,
    title: 'Étoile Bleue Urgence',
    shortTitle: 'Merci',
    category: 'intro',
    layout: 'hero',
    subtitle: 'Intervenir mieux, documenter mieux, coordonner mieux.',
    bullets: ['Prochaine étape : garde supervisée avec référent.'],
    notes: 'Remercier les participants et confirmer le suivi.',
  },
];
